- name: kubectl label node k8s-wk-1
  ansible.builtin.shell: kubectl label node k8s-wk-1 node-role.kubernetes.io/worker=

- name: kubectl label node k8s-wk-2
  ansible.builtin.shell: kubectl label node k8s-wk-2 node-role.kubernetes.io/worker=

- name: kubectl label node k8s-wk-3
  ansible.builtin.shell: kubectl label node k8s-wk-3 node-role.kubernetes.io/worker=
