lb:
  hosts:
    k8s-lb-1:
      ansible_host: 192.168.11.100

cp:
  hosts:
    k8s-cp-1:
      ansible_host: 192.168.11.111

cp_join:
  hosts:
    k8s-cp-2:
      ansible_host: 192.168.11.112
    k8s-cp-3:
      ansible_host: 192.168.11.113

worker:
  hosts:
    k8s-wk-1:
      ansible_host: 192.168.11.121
    k8s-wk-2:
      ansible_host: 192.168.11.122
    k8s-wk-3:
      ansible_host: 192.168.11.123

control_plane:
  children:
    cp:
    cp_join:

all_node:
  children:
    control_plane:
    worker:
