variables:
  k8s:
    all:
      tasks:
        # - common/sysctl.yml
        # - common/nfs-client.yml
        # - common/k8s.yml
    cp:
      tasks:
        # - cp/ha-main.yml
        # - cp/setup.yml
    cp_join:
      tasks:
        - common/sysctl.yml
        - common/nfs-client.yml
        - common/k8s_1-28.yml
        - cp/ha-backend.yml
        - cp/join.yml
    wk:
      tasks:
        # - common/sysctl.yml
        # - common/nfs-client.yml
        # - common/k8s_1-28.yml
        # - wk/ha-main.yml
        # - wk/join.yml
    wk_backup:
      tasks:
        # - common/sysctl.yml
        # - common/nfs-client.yml
        # - common/k8s_1-28.yml
        # - wk/ha-backup.yml
        # - wk/join.yml
    cp_after:
      tasks:
        # - cp/label-node.yml
        # - cp/cilium.yml
        # - cp/argocd.yml
        # - cp/postgres-operator.yml
